### ISSUE TITLE
Adding the songs to a newly created playlist

### ISSUE THREAD

**Issue by marvellous10** [Rectify-Sideproject/Create-Backend#3]
A good first-time issue to solve here would be adding songs to a playlist, you are free to edit the CreatePlaylistonSpotify function in the views.py file.

**Comment by Unlimited-demi** [comment]
Did something on this, mind checking it out?

**Comment by marvellous10** [comment]
Give me a minute

**Comment by marvellous10** [comment]
Hey noticed two major things,
1. The token being collected from the request isn't necessary, I think it'd be best to remove it.
2. The feature enhancement could be a new issue, you could do well to open a new issue about it.
For now however I'd suggest you remove the token field and make another push, I'll be waiting to open a pull request. Also make an issue for the enhancement of features. I'll edit the labels accordingly

**Comment by Unlimited-demi** [comment]
Alright, will do

**Comment by Unlimited-demi** [comment]
Hey, just to writing to confirm, I have corrected the noted points, moving on to create an issue now

**Comment by marvellous10** [comment]
Alright, seen, making a pull request now. Thanks again for contributing, I wish you the best in other OS projects
